// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCard: typeof import('element-plus/lib')['ElCard']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElInput: typeof import('element-plus/lib')['ElInput']
  }
}

export { }
